version: '3.4'

services:
  proxy.prod:
    build:
      context: proxy
      dockerfile: Dockerfile
    volumes:
      - ./proxy/certs:/etc/nginx/certs
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    environment:
      BACKEND_HOST: 'app.prod'
      HOST_NAME: 'localhost'
    depends_on:
      - app.prod
    networks:
      - default

  app.prod:
    build: .
    environment:
      CLUSTER_MODE: 'true'
    networks:
      - default

networks:
  default:
